### PR TITLE
Fix packer ansible galaxy role name

### PR DESCRIPTION
**Pull request by ortizmj12**
Fix the packer ansible galaxy role name based on https://galaxy.ansible.com/geerlingguy/packer.

### CODE REVIEW

**Comment by ortizmj12** [comment]
It looks like the failing builds are due to a conflict between ansible 2.8 and the older version of testinfra (https://github.com/ansible/molecule/issues/2083#issuecomment-499221613) that is installed as a molecule dependency. This was fixed in molecule 2.21 (https://github.com/ansible/molecule/pull/2034).

**Comment by ortizmj12** [comment]
woot! I finally have a successful build!

A couple things of note:
- I modified it to use ruby-2.6.3. The project was pinned to ruby-2.3, which is EOL, and some of the gems required >=2.4.
- I also had to modify the test to assert the inspec version. After modifying the project to use ruby-2.6.3, a newer version of inspec was being used, which caused the test to confirm the older inspec version to fail.

IIRC most if not all of the other changes are related to fixing ansible-lint errors since they've updated a bunch of their rules.

cc: @secfigo @raghunath24

**Comment by secfigo** [comment]
Thanks @ortizmj12  this is great work, I'm merging this into dev now.

**Comment by ortizmj12** [comment]
Awesome, thanks @secfigo!

**Comment by JonZeolla** [comment]
Nice work @ortizmj12 !

**Comment by ortizmj12** [comment]
Thanks @JonZeolla! :)

**Pull request merged**
